export const COLORSTITLE: {
  [name: string]: string;
} = {
  '/comedy': '_comedy',
  '/horror': '_horror',
  '/adventure': '_adventure',
  '/thriller': '_thriller',
  '/melodrama': '_melodrama',
  '/fantasy': '_fantasy',
  '/action': '_action',
  '/family': '_family',
  '/drama': '_drama',
  '/crime': '_crime',
  '/cartoon': '_cartoon',
  '/anime': '_anime',
  '/military': '_military',
  '/history': '_history',
  '/biography': '_biography',
  '/detective': '_detective',
  '/fiction': '_fiction',
  '/western': '_western',
  '/musical': '_musical',
  '/sport': '_sport',
  '/music': '_music',
  '/documentary': '_documentary',
  '/short-film': '_short-film',
  '/news': '_news',
  '/concert': '_concert',
  '/for-adults': '_for-adults',
  '/ceremony': '_ceremony',
  '/live': '_live',
  '/game': '_game',
  '/for-children': '_for-children',
  '/talk-show': '_talk-show',
  '/romance': '_romance',
  '/show': '_show'
};
