export const COLORS: {
  [name: string]: string;
} = {
  комедия: '_comedy',
  ужасы: '_horror',
  приключения: '_adventures',
  триллер: '_thriller',
  мелодрама: '_melodrama',
  фэнтези: '_fantasy',
  боевик: '_action',
  семейный: '_family',
  драма: '_drama',
  криминал: '_crime',
  мультфильм: '_cartoon',
  аниме: '_anime',
  военный: '_military',
  история: '_history',
  биография: '_biography',
  детектив: '_detective',
  фантастика: '_fiction',
  вестерн: '_western',
  музыка: 'music',
  мюзикл: 'musical',
  спорт: 'sport',
  документальный: 'documentary',
  короткометражка: 'short-film',
  новости: 'news',
  концерт: 'concert',
  'для взрослых': 'for-adults',
  церемония: 'ceremony',
  'реальное ТВ': 'real-tv',
  игра: 'game',
  'ток-шоу': 'talk-show',
  детский: 'baby'
};
