export const COLORS: {
  [name: string]: string;
} = {
  комедия: '_comedy',
  ужасы: '_horror',
  приключения: '_adventures',
  триллер: '_thriller',
  мелодрама: '_melodrama',
  фэнтези: '_fantasy',
  боевик: '_action',
  семейный: '_family',
  драма: '_drama',
  криминал: '_crime',
  мультфильм: '_cartoon',
  аниме: '_anime',
  военный: '_military',
  история: '_history',
  биография: '_biography',
  детектив: '_detective',
  фантастика: '_fiction',
  вестерн: '_western',
  мюзикл: '_musical',
  спорт: '_sport',
  музыка: '_music',
  документальный: '_documentary',
  короткометражка: '_short-film',
  новости: '_news',
  концерт: '_concert',
  'для взрослых': '_for-adults',
  церемония: '_ceremony',
  'реальное ТВ': '_real-tv',
  игра: '_game',
  детский: '_children',
  'ток-шоу': '_talk-show'
};
