export const GENRES: {
  [name: string]: string;
} = {
  comedy: 'комедия',
  horror: 'ужасы',
  adventure: 'приключения',
  adventures: 'приключения',
  thriller: 'триллер',
  fantasy: 'фэнтези',
  action: 'боевик',
  family: 'семейный',
  drama: 'драма',
  crime: 'криминал',
  cartoon: 'мультфильм',
  anime: 'аниме',
  military: 'военный',
  history: 'история',
  biography: 'биография',
  detective: 'детектив',
  fiction: 'фантастика',
  western: 'вестерн',
  musical: 'мюзикл',
  sport: 'спорт',
  music: 'музыка',
  documentary: 'документальный',
  'short-film': 'короткометражный',
  news: 'новости',
  concert: 'концерт',
  'for-adults': 'для взрослых',
  ceremony: 'церемония',
  live: 'live TV',
  game: 'игра',
  children: 'детский',
  'for-children': 'детские программы',
  'talk-show': 'ток-шоу',
  romance: 'мелодрама',
  melodrama: 'мелодрама',
  show: 'телешоу',
  'real-tv': 'реальное ТВ'
};
