export const COLORSTITLENAME: {
  [name: string]: string;
} = {
  комедия: '/comedy',
  ужасы: '/horror',
  приключения: '/adventures',
  триллер: '/thriller',
  мелодрама: '/melodrama',
  фэнтези: '/fantasy',
  боевик: '/action',
  семейный: '/family',
  драма: '/drama',
  криминал: '/crime',
  мультфильм: '/cartoon',
  аниме: '/anime',
  военный: '/military',
  история: '/history',
  биография: '/biography',
  детектив: '/detective',
  фантастика: '/fiction',
  вестерн: '/western',
  мюзикл: '/musical',
  спорт: '/sport',
  музыка: '/music',
  документальный: '/documentary',
  короткометражка: '/short-film',
  новости: '/news',
  концерт: '/concert',
  'для взрослых': '/for-adults',
  церемония: '/ceremony',
  'реальное ТВ': '/real-tv',
  игра: '/game',
  детский: '/children',
  'ток-шоу': '/talk-show'
};
