export const COLORS_TITLE_NAME: {
  [name: string]: string;
} = {
  '/comedy': 'Комедии',
  '/horror': 'Хоррор',
  '/adventure': 'Приключения',
  '/thriller': 'Триллер',
  '/fantasy': 'Фэнтези',
  '/action': 'Боевики',
  '/family': 'Для всей семьи',
  '/drama': 'Драма',
  '/crime': 'Криминал',
  '/cartoon': 'Мультфильмы',
  '/anime': 'Аниме',
  '/military': 'Военный',
  '/history': 'История',
  '/biography': 'Биография',
  '/detective': 'Детектив',
  '/fiction': 'Фантастика',
  '/western': 'Вестерн',
  '/musical': 'Мюзикл',
  '/sport': 'Спорт',
  '/music': 'Музыка',
  '/documentary': 'Документальный',
  '/short-film': 'Короткометражный',
  '/news': 'Новости',
  '/concert': 'Концерт',
  '/for-adults': 'Для взрослых',
  '/ceremony': 'Церемония',
  '/live': 'Live TV',
  '/game': 'Игра',
  '/for-children': 'Детские программы',
  '/talk-show': 'Ток-шоу',
  '/romance': 'Мелодрама',
  '/show': 'Телешоу'
};
